name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          make fmt
  unit-test:
    name: Unit Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.33.1
      - run: |
          make lint
      - run: |
          make validate
  integration-test:
    name: Integration Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.2"
      - run: |
          make test
  semantic-release:
    name: Semantic Release (dry-run)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Release
        run: |
          npm install -g semantic-release              \
            "@semantic-release/changelog"              \
            "@semantic-release/commit-analyzer"        \
            "@semantic-release/exec"                   \
            "@semantic-release/git"                    \
            "@semantic-release/github"                 \
            "@semantic-release/release-notes-generator"
          npx semantic-release --dry-run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
